import Head from 'next/head'
import Layout from "../components/Layouts/Layout/Layout";
import Home from "../components/Routes/Home/Home";

export default function HomePage() {
  return (
    <Layout>
      <Head>
        <title>Happy Miles Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </Layout>
  )
}